#!/usr/bin/bash
# [MISE] hide=true
# [MISE] sources=["Cargo.toml", "Cargo.lock"]
# [MISE] env={RUSTFLAGS="-C target-feature=+crt-static"}

set -o errexit
set -o pipefail

rustup update
rustup target add armv7-unknown-linux-musleabihf x86_64-unknown-linux-musl aarch64-unknown-linux-musl x86_64-unknown-linux-gnu
rustup component add clippy
rustup component add rustfmt
