#!/usr/bin/env python
# [MISE] description="Extract CI info"
# [MISE] hide=true
import glob
import json
import logging
import os
import re
import subprocess
import tomllib
from datetime import datetime
from io import StringIO
from pprint import pformat

LOG = logging.getLogger(__name__)


class Output:
    def __init__(self):
        output = os.getenv("GITHUB_OUTPUT")
        if output:
            self._fobj = open(output, "a")
        else:
            self._fobj = StringIO()
        self._build_id = datetime.now().strftime("%Y%m%d%H%M")

    def write(self, mise_config):
        LOG.debug("Creating outputs")
        for name in dir(self):
            if name.startswith("_"):
                continue
            if name == "write":
                continue

            output_name = name.replace("_", "-")
            value = getattr(self, name)(mise_config)
            line = f"{output_name}={json.dumps(value)}\n"
            self._fobj.write(line)
            LOG.debug(line.strip())

    def ci_tasks(self, mise_config):
        return mise_config["tasks"]["ci"]["depends"]

    def _has_source_changes(self, mise_config):
        base_sha = git(["git", "rev-list", "--tags", "--max-count=1"])
        LOG.debug("Last tag has sha %s", base_sha)
        head_sha = git(["git", "rev-parse", "HEAD"])
        LOG.debug("Head has sha %s", head_sha)
        changed_files = git(["git", "diff", "--name-only", base_sha, head_sha])
        LOG.debug("Changed files: %s", pformat(changed_files))
        sources = mise_config["tasks"]["build"]["sources"]
        sources.append(".github/workflows/*.y*ml")
        for src in sources:
            pattern = re.compile(glob.translate(src, recursive=True))
            for f in changed_files:
                if pattern.match(f):
                    LOG.debug("Found changed source file: %r", f)
                    return True
        LOG.debug("No changes to source files")
        return False

    def run_publish(self, mise_config):
        if not self._has_source_changes(mise_config):
            LOG.info("No changes to sources since last tag, no need to publish")
            return False
        result = git(["git", "rev-parse", "--symbolic-full-name", "HEAD"])
        rev = ("".join(result)).strip()
        if "refs/heads/main" != rev:
            LOG.info(f"Not on main branch, rev is {rev!r}")
            return False
        return True

    def artifacts(self, mise_config):
        build_config = mise_config["tasks"]["build"]
        return "\n".join(build_config.get("outputs", []))

    def _version(self, mise_config, clean=False):
        vars = mise_config.get("vars", {})
        major = vars.get("major_version", "0")
        if clean:
            return f"{major}.{self._build_id}"
        result = git(["git", "describe", "--always", "--dirty", "--exclude", "*"])
        local = ("".join(result)).strip()
        return f"{major}.{self._build_id}+{local}"

    def version(self, mise_config):
        return self._version(mise_config, clean=False)

    def clean_version(self, mise_config):
        return self._version(mise_config, clean=True)


def git(cmd):
    p = subprocess.run(cmd, capture_output=True, text=True)
    return p.stdout


def load_mise():
    """Load mise.toml"""
    root = os.getenv("MISE_CONFIG_ROOT", ".")
    mise_path = os.path.join(root, "mise.toml")
    with open(mise_path, "rb") as fobj:
        return tomllib.load(fobj)


def setup_logging():
    logging.basicConfig(level=logging.DEBUG, format="::%(levelname)s::%(message)s")
    # GitHub wants lowercase levelnames for workflow commands mapping
    for level in logging.getLevelNamesMapping().values():
        logging.addLevelName(level, logging.getLevelName(level).lower())


def main():
    setup_logging()
    LOG.info("Extracting CI info")
    mise_config = load_mise()
    output = Output()
    output.write(mise_config)


if __name__ == "__main__":
    main()
