#!/usr/bin/env python
# [MISE] description="Extract CI info"
# [MISE] hide=true
import json
import os
import subprocess
import sys
import tomllib
from datetime import datetime
from io import StringIO


class Output:
    def __init__(self):
        output = os.getenv("GITHUB_OUTPUT")
        if output:
            self._fobj = open(output, "a")
        else:
            self._fobj = StringIO()

    def write(self, mise_config):
        print("Creating outputs")
        for name in dir(self):
            if name.startswith("_"):
                continue
            if name == "write":
                continue

            output_name = name.replace("_", "-")
            value = getattr(self, name)(mise_config)
            line = f"{output_name}={json.dumps(value)}\n"
            self._fobj.write(line)
            sys.stdout.write(line)

    def ci_tasks(self, mise_config):
        return mise_config["tasks"]["ci"]["depends"]

    def run_publish(self, mise_config):
        p = subprocess.run(["git", "rev-parse", "--symbolic-full-name", "HEAD"], capture_output=True, text=True)
        rev = ("".join(p.stdout)).strip()
        if "refs/heads/main" != rev:
            print(f"Not on main branch, rev is {rev!r}")
            return False
        return True

    def artifacts(self, mise_config):
        build_config = mise_config["tasks"]["build"]
        return "\n".join(build_config.get("outputs", []))

    def _version(self, mise_config, clean=False):
        vars = mise_config.get("vars", {})
        major = vars.get("major_version", "0")
        minor = datetime.now().strftime("%Y%m%d%H%M")
        if clean:
            return f"{major}.{minor}"
        p = subprocess.run(["git", "describe", "--always", "--dirty", "--exclude", "*"], capture_output=True, text=True)
        local = ("".join(p.stdout)).strip()
        return f"{major}.{minor}+{local}"

    def version(self, mise_config):
        return self._version(mise_config, clean=False)

    def clean_version(self, mise_config):
        return self._version(mise_config, clean=True)


def load_mise():
    """Load mise.toml"""
    root = os.getenv("MISE_CONFIG_ROOT", ".")
    mise_path = os.path.join(root, "mise.toml")
    with open(mise_path, "rb") as fobj:
        return tomllib.load(fobj)


def main():
    print("Extracting CI info")
    mise_config = load_mise()
    output = Output()
    output.write(mise_config)


if __name__ == "__main__":
    main()
