["rust:build"]
hide = true
depends = ["rust:build-target"]

["rust:release-build"]
hide = true
depends = [
    "rust:build-target --release armv7-unknown-linux-gnueabihf",
    "rust:build-target --release x86_64-unknown-linux-gnu",
    "rust:build-target --release aarch64-unknown-linux-gnu",
]
