#!/usr/bin/env bash
# [MISE] hide=true
# [MISE] depends=["python:setup"]

set -o errexit
set -o pipefail

if [[ -e poetry.lock ]]; then
  poetry run pytest
elif [[ -e uv.lock ]]; then
  uv run pytest
fi
