#!/usr/bin/env bash
# [MISE] description="Assemble manifests into a single deploy.yaml for for kubectl apply"
# [MISE] tools={"pipx:jinja2-cli"="latest"}
# [USAGE] arg "<templates_dir>" help="Directories containing templates to assemble into a manifest"
# [USAGE] arg "[output]" help="File to write to. default=${MISE_CONFIG_ROOT}/deploy.yaml"
# [USAGE] arg "[image]" help="Override the image created. default=ghcr.io/mortenlj/$(basename ${MISE_PROJECT_ROOT})"

set -o errexit
set -o pipefail

IMAGE="ghcr.io/${usage_image:-ghcr.io/mortenlj/$(basename "${MISE_PROJECT_ROOT}")}"
VERSION="${MORTENLJ_MISE_LIB_VERSION:-latest}"

export IMAGE
export VERSION

output=$(mktemp deploy-XXXXXX --suffix=".yaml")

for template in "${usage_templates_dir?}"/*.j2; do
  jinja2 "${template}" >> "${output?}"
done

for plain in "${usage_templates_dir?}"/*.yaml; do
  cat "${plain}" >> "${output?}"
done

mv "${output}" "${usage_output:-${MISE_CONFIG_ROOT}/deploy.yaml}"
