FROM jdxcode/mise:latest

WORKDIR /app

COPY .config ./.config
COPY mise.toml ./mise.toml
RUN mise trust mise.toml

RUN mise run docker-prepare || true

COPY . ./
ARG task
ARG MISE_LIB_VERSION
ARG MISE_LIB_CLEAN_VERSION
RUN mise run ${task}
RUN find > filelist.txt
