#!/usr/bin/bash
# [MISE] hide=true
# [MISE] depends=["rust:setup"]
# [USAGE] arg "[target]" help="Target triple" {
# [USAGE]   choices "armv7-unknown-linux-gnueabihf" "x86_64-unknown-linux-gnu" "aarch64-unknown-linux-gnu" "x86_64-unknown-linux-musl" "aarch64-unknown-linux-musl"
# [USAGE] }
# [USAGE] flag "--release" help="Build release mode"

set -o errexit
set -o pipefail

# Inserts version and target into filename before extension or at end if no extension
insert_version_target() {
  local filename="${1?}"
  local version="${2?}"
  local target="${3?}"
  local base ext new_name

  # Extract base and extension
  if [[ "${filename}" =~ ^(.+)\.(.+)$ ]]; then
    base="${BASH_REMATCH[1]}"
    ext=".${BASH_REMATCH[2]}"
    new_name="${base}.${version}.${target}${ext}"
  else
    new_name="${filename}.${version}.${target}"
  fi
  echo "${new_name}"
}

default_target=$(rustup show | grep "Default host" | awk '{ print $3 }')
target="${usage_target:-${default_target}}"

RUSTFLAGS="-C target-feature=+crt-static"

# shellcheck disable=SC2154
case ${target} in
  armv7-unknown-linux-gnueabihf)
    export CARGO_TARGET_ARMV7_UNKNOWN_LINUX_GNUEABIHF_LINKER=clang
    RUSTFLAGS="${RUSTFLAGS} -C link-arg=--target=armv7-unknown-linux-gnueabihf -C link-arg=-fuse-ld=lld"
    ;;
  aarch64-unknown-linux-gnu)
    export CARGO_TARGET_AARCH64_UNKNOWN_LINUX_GNU_LINKER=clang
    RUSTFLAGS="${RUSTFLAGS} -C link-arg=--target=aarch64-unknown-linux-gnu -C link-arg=-fuse-ld=lld"
    ;;
  aarch64-unknown-linux-musl)
    export CARGO_TARGET_AARCH64_UNKNOWN_LINUX_MUSL_LINKER=clang
    RUSTFLAGS="${RUSTFLAGS} -C link-arg=--target=aarch64-unknown-linux-musl -C link-arg=-fuse-ld=lld"
    ;;
  x86_64-unknown-linux-gnu)
    export CARGO_TARGET_X86_64_UNKNOWN_LINUX_GNU_LINKER=clang
    RUSTFLAGS="${RUSTFLAGS} -C link-arg=--target=x86_64-unknown-linux-gnu -C link-arg=-fuse-ld=lld"
    ;;
  x86_64-unknown-linux-musl)
    export CARGO_TARGET_X86_64_UNKNOWN_LINUX_MUSL_LINKER=clang
    RUSTFLAGS="${RUSTFLAGS} -C link-arg=--target=x86_64-unknown-linux-musl -C link-arg=-fuse-ld=lld"
    ;;
esac

export RUSTFLAGS

# shellcheck disable=SC2086
cargo build --target ${target} ${usage_release:+--release}

if [[ "${usage_release}" == "true" ]]; then
  profile="release"
else
  profile="debug"
fi

if [[ "${target}" != "" ]]; then
  for f in "target/${target}/${profile}/"*; do
    if [[ -x "${f}" && -f "${f}" ]]; then
      new_name="target/${profile}/$(insert_version_target "$(basename "${f}")" "${MORTENLJ_MISE_LIB_VERSION:-0.0}" "${target}")"
      echo "Copying '${f}' to '${new_name}'"
      cp "${f}" "${new_name}"
    fi
  done
fi
