#!/usr/bin/bash
# [MISE] hide=true
# [MISE] sources=["Cargo.toml", "Cargo.lock"]
# [MISE] tools={"cargo-binstall"="latest"}

set -o errexit
set -o pipefail

SUDO=''
if (( $EUID != 0 )); then
    SUDO='sudo'
fi

update_needed="yes"
function install_if_needed {
  local bin=${1?}
  local pkg=${2-${bin}}
  if ! command -v "${bin}"; then
    echo "Needs to install ${pkg} ..."
    if [[ -n "${update_needed}" ]]; then
      ${SUDO} apt-get --yes update
      update_needed=""
    fi
    ${SUDO} apt-get --yes install "${pkg}"
  fi
}

RUSTFLAGS="-C target-feature=+crt-static"
export RUSTFLAGS

install_if_needed zig

rustup update
rustup target add armv7-unknown-linux-musleabihf x86_64-unknown-linux-musl aarch64-unknown-linux-musl
rustup component add clippy
rustup component add rustfmt
cargo binstall --no-confirm --no-cleanup cargo-nextest
cargo binstall --no-confirm --no-cleanup cargo-chef
cargo binstall --no-confirm --no-cleanup cargo-zigbuild
