#!/usr/bin/bash
# [MISE] hide=true
# [MISE] sources=["Cargo.toml", "Cargo.lock"]
# [MISE] tools={"cargo-binstall"="latest"}

set -o errexit
set -o pipefail

SUDO=''
if (( $EUID != 0 )); then
    SUDO='sudo'
fi

update_needed="yes"
function install_if_needed {
  local bin=${1?}
  local pkg=${2-${bin}}
  if ! command -v "${bin}"; then
    echo "Needs to install ${pkg} ..."
    if [[ -n "${update_needed}" ]]; then
      ${SUDO} apt-get --yes update
      update_needed=""
    fi
    ${SUDO} apt-get --yes install "${pkg}"
  fi
}

RUSTFLAGS="-C target-feature=+crt-static"
export RUSTFLAGS

install_if_needed clang
install_if_needed lld
install_if_needed cmake
install_if_needed musl-gcc musl-tools

# Download musl.cc cross-compilation sysroots
if [[ ! -d /opt/aarch64-linux-musl-cross ]]; then
  curl -fsSL https://musl.cc/aarch64-linux-musl-cross.tgz | ${SUDO} tar xz -C /opt/
fi
if [[ ! -d /opt/armv7l-linux-musleabihf-cross ]]; then
  curl -fsSL https://musl.cc/armv7l-linux-musleabihf-cross.tgz | ${SUDO} tar xz -C /opt/
fi

rustup update
rustup target add armv7-unknown-linux-musleabihf x86_64-unknown-linux-musl aarch64-unknown-linux-musl
rustup component add clippy
rustup component add rustfmt
cargo binstall --no-confirm --no-cleanup cargo-nextest
cargo binstall --no-confirm --no-cleanup cargo-chef
