#!/usr/bin/bash
# [MISE] hide=true
# [MISE] depends=["rust:setup"]
# [MISE] tools={"cargo-binstall"="latest","cargo:cargo-nextest"="latest"}

set -o errexit
set -o pipefail

cargo nextest run --no-tests warn
