#!/usr/bin/bash
# [MISE] hide=true
# [MISE] depends=["rust:setup"]

set -o errexit
set -o pipefail

default_target=$(rustup show | grep "Default host" | awk '{ print $3 }')

RUSTFLAGS="-C target-feature=+crt-static"
export RUSTFLAGS

cargo nextest run --target "${default_target}" --no-tests warn
