name: build docker

on:
  workflow_call:
    inputs:
      version:
        description: Version to use for image tag (clean)
        required: true
        type: string
      clean-version:
        description: Version to use for image tag (clean)
        required: true
        type: string
      release-build-tasks:
        description: JSON data with tool versions in use in this project
        required: true
        type: string
      artifacts:
        description: Artifacts produced by the release-build tasks
        required: true
        type: string

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    permissions:
      contents: read
    strategy:
      matrix:
        task: ${{ fromJSON(inputs.release-build-tasks) }}
    steps:
      - uses: jdx/mise-action@3c2e0cf82a5b2e5249f0d3635a4d83d0ae861518 # v4.2.5
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          fetch-depth: 0
          submodules: "true"
          persist-credentials: false
      - run: mise run release-build
        env:
          MORTENLJ_MISE_LIB_VERSION: ${{ inputs.version }}
          MORTENLJ_MISE_LIB_CLEAN_VERSION: ${{ inputs.clean-version }}
      - name: Save artifacts for release
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: artifacts-${{ matrix.task.name }}
          path: |
            ${{ fromJSON(inputs.artifacts) }}
          if-no-files-found: error
