name: build docker

on:
  workflow_call:
    inputs:
      main-image:
        description: The full image to produce (without tag)
        required: true
        type: string
      clean-version:
        description: Version to use for image tag (clean)
        required: true
        type: string
      tool-versions:
        description: JSON data with tool versions in use in this project
        required: true
        type: string
      main-branch:
        description: The ref of the main branch in this repo
        required: false
        type: string
        default: refs/heads/main
      manifests-task:
        description: The task used to generate manifests
        required: false
        type: string
        default: k8s:manifests
    secrets:
      GHCR_PASSWORD:
        required: true


jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    permissions:
      packages: write
      checks: write
      pull-requests: write
    steps:
      - uses: jdx/mise-action@d16887ba50704baed7de72bd1e82e04391e4457a # v3
      - name: Set up QEMU
        id: qemu
        uses: docker/setup-qemu-action@c7c53464625b32c7a7e944ae62b3e17d2b600130 # v3
        with:
          image: tonistiigi/binfmt:latest
          platforms: all
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to GitHub Packages Docker Registry
        uses: docker/login-action@5e57cd118135c172c3672efd75eb46360885c0ef # v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_PASSWORD }}
      - uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v6
        with:
          fetch-depth: 0
          submodules: "true"
      - name: Build and possibly push docker image
        uses: docker/build-push-action@v6
        with:
          context: "."
          push: '${{ github.ref == inputs.main-branch }}'
          platforms: linux/amd64,linux/arm64
          build-args: |
            MORTENLJ_MISE_LIB_CLEAN_VERSION=${{ inputs.clean-version }}
            PY_VERSION=${{ fromJSON(inputs.tool-versions).python[0] }}
            RUST_VERSION=${{ fromJSON(inputs.tool-versions).rust[0] }}
          tags: |
            ${{ inputs.main-image }}:${{ inputs.clean-version }}
            ${{ inputs.main-image }}:latest
      - name: Assemble manifests
        run: mise run "${{ inputs.manifests-task }}" "${{ inputs.main-image }}"
        env:
          MORTENLJ_MISE_LIB_CLEAN_VERSION: ${{ inputs.clean-version }}
      - name: Save manifests for later deploy
        uses: actions/upload-artifact@b7c566a772e6b6bfb58ed0dc250532a479d7789f # v6
        with:
          name: manifests
          path: mise-output/*.yaml
