name: build docker

on:
  workflow_call:
    inputs:
      ci-tasks:
        description: JSON data with ci tasks in use in this project
        required: true
        type: string

jobs:
  ci:
    name: CI
    runs-on: ubuntu-latest
    permissions:
      contents: read
    strategy:
      matrix:
        task: ${{ fromJSON(inputs.ci-tasks) }}
    steps:
      - uses: jdx/mise-action@1648a7812b9aeae629881980618f079932869151 # v4
      - uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v6
        with:
          fetch-depth: 0
          submodules: "true"
      - run: mise run ${{ matrix.task.cmd }}
