name: build docker

on:
  workflow_call:
    inputs:
      ci-tasks:
        description: JSON data with ci tasks in use in this project
        required: true
        type: string

jobs:
  ci:
    name: CI
    runs-on: ubuntu-latest
    strategy:
      matrix:
        task: ${{ fromJSON(inputs.ci-tasks) }}
    steps:
      - uses: jdx/mise-action@3c2e0cf82a5b2e5249f0d3635a4d83d0ae861518 # v4.2.5
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          fetch-depth: 0
          submodules: "true"
      - run: mise run ${{ matrix.task.cmd }}
