name: cleanup

on:
  workflow_call:
    inputs:
      main-branch:
        description: The ref of the main branch in this repo
        required: false
        type: string
        default: refs/heads/main

jobs:
  cleanup:
    name: Cleanup
    if: '${{ github.ref == inputs.main-branch }}'
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - name: Cleanup main images
        uses: dataaxiom/ghcr-cleanup-action@cd0cdb900b5dbf3a6f2cc869f0dbb0b8211f50c4 # v1.0.16
        with:
          keep-n-tagged: 5
          older-than: 2 weeks
          delete-untagged: true
          delete-ghost-images: true
          delete-orphaned-images: true
          delete-partial-images: true
