name: setup

on:
  workflow_call:
    outputs:
      ci-tasks:
        value: ${{ jobs.setup.outputs.ci-tasks }}
      run-publish:
        value: ${{ jobs.setup.outputs.run-publish }}
      artifacts:
        value: ${{ jobs.setup.outputs.artifacts }}
      tool-versions:
        value: ${{ jobs.setup.outputs.tool-versions }}
      version:
        value: ${{ jobs.setup.outputs.version }}
      clean-version:
        value: ${{ jobs.setup.outputs.clean-version }}
      release-build-tasks:
        value: ${{ jobs.setup.outputs.release-build-tasks }}


jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v6
        with:
          fetch-depth: 0
          submodules: "true"
      - uses: jdx/mise-action@d16887ba50704baed7de72bd1e82e04391e4457a # v3
      - run: mise run extract-ci-info
        id: ci-info
    outputs:
      ci-tasks: ${{ steps.ci-info.outputs.ci-tasks }}
      run-publish: ${{ steps.ci-info.outputs.run-publish }}
      artifacts: ${{ steps.ci-info.outputs.artifacts }}
      tool-versions: ${{ steps.ci-info.outputs.tool-versions }}
      version: ${{ steps.ci-info.outputs.version }}
      clean-version: ${{ steps.ci-info.outputs.clean-version }}
      release-build-tasks: ${{ steps.ci-info.outputs.release-build-tasks }}
