name: setup

on:
  workflow_call:
    outputs:
      ci-tasks:
        value: ${{ jobs.setup.outputs.ci-tasks }}
      run-publish:
        value: ${{ jobs.setup.outputs.run-publish }}
      artifacts:
        value: ${{ jobs.setup.outputs.artifacts }}
      tool-versions:
        value: ${{ jobs.setup.outputs.tool-versions }}
      version:
        value: ${{ jobs.setup.outputs.version }}
      clean-version:
        value: ${{ jobs.setup.outputs.clean-version }}
      release-build-tasks:
        value: ${{ jobs.setup.outputs.release-build-tasks }}
      manifests-task:
        value: ${{ jobs.setup.outputs.manifests-task }}


jobs:
  setup:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          fetch-depth: 0
          submodules: "true"
          persist-credentials: false
      - uses: jdx/mise-action@3c2e0cf82a5b2e5249f0d3635a4d83d0ae861518 # v4.2.5
      - run: mise run extract-ci-info
        id: ci-info
    outputs:
      ci-tasks: ${{ steps.ci-info.outputs.ci-tasks }}
      run-publish: ${{ steps.ci-info.outputs.run-publish }}
      artifacts: ${{ steps.ci-info.outputs.artifacts }}
      tool-versions: ${{ steps.ci-info.outputs.tool-versions }}
      version: ${{ steps.ci-info.outputs.version }}
      clean-version: ${{ steps.ci-info.outputs.clean-version }}
      release-build-tasks: ${{ steps.ci-info.outputs.release-build-tasks }}
      manifests-task: ${{ steps.ci-info.outputs.manifests-task }}
